### ISSUE TITLE
Blazor WASM EventCallback Tuple

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/razor-compiler#361] opened 2022-09-27 22:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have this component with an event callback with a tuple in argument:
![image](https://user-images.githubusercontent.com/23618436/192651748-0a254c69-892a-4eae-b0dd-3772ad6ab2ec.png)

```csharp
public partial class SelectBox : ComponentBase
{
    [Parameter] public RenderFragment DropDownArrow { get; set; }
    [Parameter] public string PropertyType { get; set; }
    [Parameter] public IEnumerable<ArticleProperty> Properties { get; set; }
    [Parameter] public EventCallback<(string, Guid)> OnSelect { get; set; }


    /// <summary>
    /// Propriété sélectionnée par défaut.
    /// Première propriété de la liste si non défini
    /// </summary>
    [Parameter] public Guid DefaultProperty { get; set; }

    private bool showOptions;

    protected override void OnInitialized()
    {
    }

    private async Task Select(Guid propertyValueId)
    {
        if (OnSelect.HasDelegate)
            await OnSelect.InvokeAsync((PropertyType, propertyValueId));
        showOptions = false;
    }
}
```

Parent component:
```csharp
public partial class PropertySelector : ComponentBase
{
 .....................................................

    private async Task PropertyChanged((string Type, Guid Value) property)
    {
        Console.WriteLine($"PropertyChanged : {property.Type} {property.Value}");
        SelectedProperties[property.Type] = property.Value;
        if (OnPropertyChange.HasDelegate)
            await OnPropertyChange.InvokeAsync();
    }
}
```

### Expected Behavior

This method worked in previous versions of .Net 7

### .NET Version

.Net 7 RC1

**Comment by mkArtakMSFT** [comment] 2022-10-04 16:18
@jaredpar while the customer was able to workaround this issue by changing the type parameter to a record type, I think tuples should still be supported.

**Comment by jaredpar** [comment] 2022-10-04 20:07
@333fred, @jjonescz is this another variant of the bug we've fixed?

**Comment by 333fred** [comment] 2022-10-04 21:07
Yes, this is a duplicate of https://github.com/dotnet/razor-compiler/issues/332.

**Closed by 333fred** 2022-10-04 21:07 UTC
