### ISSUE TITLE
Type Inference on generic razor components improvements 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/razor-compiler#150] opened 2021-10-14 01:00 UTC
Direct customer ask copying here:

> Type Inference on generic razor components, and then especially regarding generic event callbacks.

Example:

```
<TextBoxWithLabelFor @bind-Value="this.Model.NumberOfVehicles" 
                                               For="@(() => this.Model.NumberOfVehicles)" 
                                               Label="@_L["MaxVehicles"]" 
                                               ReadOnly="@Checker.IsDisabled(x => x.NumberOfVehicles)"
                                               T="int?"
                                               AfterValueChanged="@((e) => this.AutoSaveField(e, x => x.NumberOfVehicles))" />
```
The razor component ‘TextBoxWithLabelFor’ has a generic type parameter:
```
@using System.Linq.Expressions

@implements IValueControl<T>
@namespace Daf.Dmsc.MultiSupport.Web.Blazor.Components
@typeparam T


<div class="mb-1 row">
    @if (!String.IsNullOrEmpty(this.Label))
    {
        <label class="col-sm-4 col-form-label">@this.Label</label>
    }
    else
    {
        <LabelFor class="col-sm-4 col-form-label" For="@For" />
    }
    <div class="col-sm-8">
         <TextBoxFor Value="@this.Value"                      
                     ValueExpression="@this.For"
                     ValueChanged="@this.ValueChanged"  
                     ReadOnly="@this.ReadOnly" 
                     class="@this.GetCssString()"
                     AfterValueChanged = "@this.AfterValueChanged" />
         @if (this.UseValidation)
         {
             <ValidationMessage For="@For" />
         }
    </div>
</div>

@code
{
    [Parameter] public string Label { get; set; }
    [Parameter] public T Value { get; set; }
    [Parameter] public Expression<Func<T>> For { get; set; }
    [Parameter] public EventCallback<T> ValueChanged { get; set; }
    [Parameter] public EventCallback<ValueChangedEventArgs<T>> AfterValueChanged { get; set; }
    [Parameter] public bool UseValidation { get; set; }
    [Parameter] public string DisplayFormat { get; set; }
    [Parameter] public bool ReadOnly { get; set; }

    private string GetCssString()
                {
                               string result = "form-control";
                               if (this.ReadOnly)
                               {
                                               result += " textbox-readonly";
                               }

                               return result;
                }
}
```

As you can see, the AfterValueChanged event callback uses the same generic parameter T:
    [Parameter] public EventCallback<ValueChangedEventArgs<T>> AfterValueChanged { get; set; }

But still I have to supply the generic parameter in the razor file otherwise I get a compiler error that the type cannot be inferred.
But in my opinion the compiler should be able to infer it.

**Comment by javiercn** [comment] 2022-08-01 12:45
@CecoMilchev this was addressed in .NET 7.0 preview7 which will be available in the coming weeks

**Comment by CecoMilchev** [comment] 2022-08-01 13:15
Hi @javiercn, thank you for your feedback, I will perform the tests whenever preview 7 is live. Do you have a specific date for the release as [the milestone](https://github.com/dotnet/aspnetcore/milestone/219) has no public due date set?

Also, will it be resolved in the razor-compiler repo or the aspnetcore repo?

**Comment by javiercn** [comment] 2022-08-01 13:55
@CecoMilchev I can't give you a concrete date, but we release a preview every month. The commit that fixed this is on the compiler repo [here](0033829b5922990c1a12ab665c0a20f55bb9c0b9)

**Comment by Jcparkyn** [comment] 2022-08-20 11:04
This improvement would help a lot for the library I'm working on (which uses a lot of generics). The compiler errors when using an `EventCallback<T>` without explicit types aren't very clear to library users, so I'm almost considering just using `Action<T>` instead as a workaround (since inference works fine for that) and forgoing the benefits of `EventCallback`. There are some other issues with using explicit types that compound this:

- When using explicit types, it doesn't seem possible to mark them as nullable reference types with `?`, and the compiler doesn't give any warnings when incorrectly omitting the `?`.
- It's not possible to explicitly define only a subset of the type parameters (which is a pain for me, because my components have multiple type parameters, and some of them need to be inferred as types that users wouldn't normally use directly).
- Even when the argument type for the lambda is defined explicitly, delegates that would normally be compatible aren't, because `EventCallback` can't be co/contra-variant.

**Comment by CecoMilchev** [comment] 2022-08-23 06:37
@javiercn I can confirm the compiler error regarding the missing TItem declaration that I had with .NET7 prev5 and prev6 is fixed with prev7.

**Closed** 2022-08-23 13:48 UTC
Labels: enhancement, area-razor.compiler, Priority:2

**Comment by Jcparkyn** [comment] 2022-08-23 22:27
@javiercn I don't think this issue should've been closed?

The issue that was fixed was about allowing explicitly typed callbacks to be used (which was a regression), but the original issue in this thread was about allowing type inference on the lambda parameter (which has never worked AFAIK).
